version: 2

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

#formats:
#  - pdf

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"
  jobs:
    pre_build:
      - sphinx-apidoc -o docs/apidoc/ --private --module-first src/xclim src/xclim/testing/tests src/xclim/indicators src/xclim/indices
      - rm docs/apidoc/xclim.rst
      - env SPHINX_APIDOC_OPTIONS="members,undoc-members,show-inheritance,noindex" sphinx-apidoc -o docs/apidoc/ --private --module-first src/xclim src/xclim/testing/tests
      - sphinx-build -b linkcheck docs/ _build/linkcheck || true

conda:
  environment: environment.yml

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev
        - extras

search:
  ranking:

    notebooks/*: 2
    api_indicators.html: 1
    indices.html: -1
    _modules/*: -3
