version: 2

formats: all

build:
    image: latest

python:
  version: 3.6
  pip_install: true
  extra_requirements: docs

sphinx:
  configuration: docs/source/conf.py

conda:
  environment: readthedocs_environment.yml
