name: xclim
channels:
- conda-forge
- defaults
dependencies:
- pip
- sphinx
- nbsphinx
- ipython
- pandoc
- scipy>=1.2
- numpy>=1.15
- pandas>=0.23
- fiona>=1.8
- rtree>=0.8
- geojson>=2.5.0
- shapely>=1.6
- geopandas>=0.4
- cftime~=1.0.3.4
- netCDF4>=1.5
- dask
- bottleneck==1.3.1
- xarray==0.13.0
- pyproj==2.4.1
- pint>=0.8
- boltons>=19.0
- scikit-learn>=0.21.3
- pip:
  - guzzle-sphinx-theme
