name: Generic issue template
description: For detailing generic/uncategorized issues in Xclim

body:
  - type: textarea
    id: generic-issue
    attributes:
      label: Generic Issue
      description: Please fill in the following information fields as needed.
      value: |
        * xclim version:
        * Python version:
        * Operating System:

        ### Description
        <!--Describe what you were trying to get done.
        Tell us what happened, what went wrong, and what you expected to happen.-->

        ### What I Did
        <!--Paste the command(s) you ran and the output.
        If there was a crash, please include the traceback below.-->
        ```
        $ pip install foo --bar
        ```

        ### What I Received
        <!--Paste the output or the stack trace of the problem you experienced here.-->
        ```
        Traceback (most recent call last):
         File "/path/to/file/script.py", line 3326, in run_code
           exec(code_obj, self.user_global_ns, self.user_ns)
         File "<ipython-input-2-9e1622b385b6>", line 1, in <module>
           1/0
         ZeroDivisionError: division by zero
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Ouranosinc/xclim/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
