name: "Draft compile JOSS paper"

on:
  push:
    paths:
      - 'paper/*'

jobs:
  paper:
    runs-on: ubuntu-22.04
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: paper/paper.md
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: paper
          path: paper/paper.pdf
